### ISSUE TITLE
Create keyspace on startup

### ISSUE THREAD

**Issue by dschroe** [docker-library/cassandra#104]
Is there any way to copy a .cql script into the cassandra image which gets automatically executed as soon as cassandra is fully initialized and available on port 9042?

**Comment by rodrigorodrigues** [comment]
Hi all,

I have the same issue, is there one way to load a script after cassandra is ready?

I'm using Vagrant + docker-compose on Win 7.

**Comment by SpinGit** [comment]
Hi i have the same issue as well. I would like to configure a keyspace for my integration tests.

I'm using bitbucket pipeline and i have the following setup:
`pipelines:
  default:
    - step:
        script:
          - sleep 15
          - npm test
        services:
          - cassandra
definitions:
  services:
    cassandra:
      image: cassandra
      environment:
        MAX_HEAP_SIZE: 512M # Need to restrict the heapsize or else Cassandra will OOM
        HEAP_NEWSIZE: 128M`

I would like to have an environment variable to set the default keyspace, with an default strategey. Otherwise provisioning of an running cassandra db must be done with another docker container...

Thank you very much - Not sure if this issue is a problem of the docker image itself.

**Comment by dschroe** [comment]
Hey guys, you can solve this problem like this

https://github.com/dschroe/cassandra

**Comment by MatteoJoliveau** [comment]
@dschroe can you add a README with a short example about how to run your image?

**Comment by Chabane** [comment]
@dschroe not working, the CQL scripts are never executed

**Comment by dschroe** [comment]
Can you share your configuration?

**Comment by Chabane** [comment]
@dschroe Thanks for sharing!
If you put your configuration in the readme, I think the vote would be a more reasonable ;-)

I works with this solution https://stackoverflow.com/a/46037377

**Comment by daggerok** [comment]
I cannot use image: dschroe/cassandra-docker
but I can build from Dockerfile of repository @dschroe provided:

docker-compose.yml

```yaml
version: "2.1"

services:

  cassadnra:
    #image: dschroe/cassandra-docker
    image: 127.0.0.1:5000/cassandra
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports: ["9042:9042"]
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks: [backing-services]

volumes:
  cassandra-data: {}

networks:
  backing-services:
```

docker-entrypoint-initdb.d/init.cql

```cql

CREATE KEYSPACE IF NOT EXISTS demo WITH replication = 
{'class':'SimpleStrategy','replication_factor':'1'};
```

**Comment by hantsy** [comment]
@daggerok I am using DockerToolbox under Windows 10, it seems the `./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d` volume mapping does not work.

**Comment by daggerok** [comment]
Hi @hantsy,

unfortunately I have not testing toolbox on Windows 10
verified on Docker CE on OSX and Docker on Linux ubunru

---
Regards

**Comment by moharnab123saikia** [comment]
@dschroe Your script worked for me on OSX. Thanks.

**Comment by sourcekick** [comment]
It is a very common use-case in software development. I do not like the workaround, because it means so many people now need to build their own C* Docker Images.

I would much prefer to see support for this Issue in the official Docker image.

**Comment by veysiertekin** [comment]
I was able to initialize Cassandra without a new Docker image by inspiring above comments.

I have added `volumes` and `command` sections to my `.yml` file:

```yml
...
cassandra:
    image: cassandra:3.11.2
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
...
```

But called `docker-entrypoint.sh` within `cassandra-init.sh`.
The contents of `cassandra-init.sh`:

```sh
cat >/import.cql <<EOF
CREATE keyspace test with replication = {'class':'SimpleStrategy', 'replication_factor' : 1};
EOF

until cqlsh -f /import.cql; do
  echo "cqlsh: Cassandra is unavailable to initialize - will retry later"
  sleep 2
done &

exec /docker-entrypoint.sh "$@"
```

**Comment by veysiertekin** [comment]
I was able to initialize Cassandra without a new Docker image by inspiring above comments.

I have added `volumes` and `command` sections to my `compose.yml` file:

```yml
version: '2.1'
...
  cassandra:
    image: cassandra:3.11.2
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
...
```

But called `docker-entrypoint.sh` at the end of `cassandra-init.sh`.
The contents of `cassandra-init.sh`:

```sh
cat >/import.cql <<EOF
DROP keyspace test;
CREATE keyspace test with replication = {'class':'SimpleStrategy', 'replication_factor' : 1};
EOF

# You may add some other conditionals that fits your stuation here
until cqlsh -f /import.cql; do
  echo "cqlsh: Cassandra is unavailable to initialize - will retry later"
  sleep 2
done &

exec /docker-entrypoint.sh "$@"
```

**Comment by veselinnguyen** [comment]
Why the issue has been closed? Has someone found already a solution?

**Comment by fogrizovic** [comment]
Hi,
I have succesfully tried the approach from @veysiertekin . 

**docker-compose.yml**
```
cassandra:
    image: cassandra:2.1.20
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
```
**cassandra-init.sh**
```
cat >/import.cql <<EOF
DROP keyspace name;
CREATE KEYSPACE name WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'} AND durable_writes = true;
EOF

until cqlsh -f /import.cql; do
  echo "cqlsh: Cassandra is unavailable to initialize - will retry later"
  sleep 2
done &

exec /docker-entrypoint.sh "$@"
```
**import.cql**
`CREATE TABLE name.blabla (search_hash text, PRIMARY KEY (search_hash));`
