### ISSUE TITLE
bash: line 1: 9 killed /docker-entrypoint.sh cassandra -f and  exited with code 137 on Windows 10 

### ISSUE THREAD

**Issue by shengnian** [docker-library/cassandra#107]
i use docker-compose to compose the cassandra cluster on window 10,  when docker service cassandra2 (sleep 60s) bootstrap the cassandra1 service will log error:
```
cassandra1 bash: line1: 9 Kllled      /docker-entrypoint.sh cassandra -f
cassandra1 exited with code 137
```
Docker version:
Community Editioin
Version 17.03.1-ce-win12(12058)

The `docker-compose.yml`:
```
version: '3'
services:
    cassandra1:
        image: cassandra:3.10
        container_name: cassandra1
        hostname: cassandra1
        command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f'
        networks:
            - cassnet
#        volumes:
#            - ./data1:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=cass_cluster
            - CASSANDRA_SEEDS=cassandra1
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
    cassandra2:
        image: cassandra:3.10
        container_name: cassandra2
        hostname: cassandra2
        command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 60; fi && /docker-entrypoint.sh cassandra -f'
        networks:
            - cassnet
#        volumes:
#            - ./data2:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=cass_cluster
            - CASSANDRA_SEEDS=cassandra1
        depends_on:
              - cassandra1
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
    cassandra3:
        image: cassandra:3.10
        container_name: cassandra3
        hostname: cassandra3
        command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 120; fi && /docker-entrypoint.sh cassandra -f'
        networks:
            - cassnet
#       volumes:
#            - ./data3:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=cass_cluster
            - CASSANDRA_SEEDS=cassandra1
        depends_on:
              - cassandra1
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
networks:
    cassnet:
```
