### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by measwel** [docker-library/cassandra#123]
I am trying to start a cassandra node in docker with:

```
 DC1_CASSANDRA_SEED:
      image: cassandra:3.10
      # image: 'bitnami/cassandra:latest'
      # sleep if starting for the first time. For each next node, sleep extra 60 sec.
      command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f'
      
      # map local folder for data persistency
      volumes:
        - ./volumes/cassandra_seed_data:/var/lib/cassandra:rw
        # - ./volumes/cassandra_seed_data:/bitnami 
      # Docker constainer environment variable. We are using the
      # CASSANDRA_CLUSTER_NAME to name the cluster. This needs to be the same
      # across clusters. We are also declaring that DC1_CASSANDRA_SEED is a seed node.
      environment:
          - CASSANDRA_CLUSTER_NAME=arbotti_cluster
          - CASSANDRA_SEEDS=DC1_CASSANDRA_SEED
          - CASSANDRA_PASSWORD_SEEDER=yes
          - CASSANDRA_PASSWORD=password123  
      # Exposing ports for inter cluster communication
      expose:
            - 7000
            - 7001
            - 7199
            - 9160
      # Exposing ports on host => host_port:docker_port
      ports:
        - "9042:9042"
      # Cassandra ulimt recommended settings
      ulimits:
          memlock: -1
          nproc: 32768
          nofile: 100000
      
      # labels:
      # kompose.service.type: nodeport
        
      networks:
        - arbotti_DC1
```

Every time this ends with the error:
`ERROR [main] 2017-11-28 22:17:46,792 CassandraDaemon.java:752 - Has no permission to create directory /var/lib/cassandra/data`

What should I do to enable the Daemon to make the directory?
