### ISSUE TITLE
How can a snapshot be restored

### ISSUE THREAD

**Issue by hanckmann** [docker-library/cassandra#224]
The docker container works.
I like to use it in a docker-compose scenario, where my compose file contains:

```
version: '3'

volumes:
  local_cassandra_data: {}

services:
  cassandra:
    build:
      context: .
      dockerfile: ../cassandra/Dockerfile
    image: staal_cassandra
    container_name: staal_cassandra
    volumes:
      - local_cassandra_data:/var/lib/cassandra:Z
    ports:
      - "7000:7000"
      - "7001:7001"
      - "9042:9042"
      - "9160:9160"
      - "7199:7199"
    environment:
      - "LOCAL_JMX=no"
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
```

The referenced Dockerfile contains:

```
FROM cassandra:3

# Require user & pass for accessing Cassandra instance within container
# COPY ./cassandra.yaml /etc/cassandra/
RUN echo "authenticator: PasswordAuthenticator" >> /etc/cassandra/cassandra.yaml &&\
    echo "monitorRole QED" >> /etc/cassandra/jmxremote.password &&\
    echo "controlRole R&D" >> /etc/cassandra/jmxremote.password &&\
    echo "cassandra cassandra" >> /etc/cassandra/jmxremote.password
```

My issue is that I have been trying for most of the day, but did not manage to restore a snapshot of an existing Cassandra database.

It would be really great if you could give me a pointer to how to do this.
