### ISSUE TITLE
Cassandra doesn't run with a low memory on docker

### ISSUE THREAD

**Issue by rodrigorodrigues** [docker-library/cassandra#277]
Hi all,

I'm trying to run Cassandra with the minimum memory as possible on docker but the server kills after a while, is there anyway to use Cassandra with a minimum memory possible? It could disable most all features like authorization, cluster just need a simple single node to store data in a fast way.

    cassandra:
      image: 'cassandra:latest'
      environment:
        - 'HEAP_NEWSIZE=10M'
        - 'MAX_HEAP_SIZE=200M'
      ports:
        - '9042:9042'
      deploy:
        resources:
          limits:
            cpus: "0.5"
            memory: "300MB"

**Comment by tianon** [comment]
Hmm, I'm not sure. I've never had much luck with _limiting_ Cassandra explicitly -- using `--env MAX_HEAP_SIZE='128m' --env HEAP_NEWSIZE='32m'` is the best I've found to keep the memory usage low (which is very similar to what you're using).  If you get rid of the explicit limit (or raise it), does that help?

(This might be better suited to a Java or Cassandra specific forum, since it's not really specific to the container image, and then you might find folks with more knowledge of Java and Cassandra memory usage and keeping it within sane thresholds. :sweat_smile:)

**Comment by LaurentGoderre** [comment]
I haven't tried yet but according to the docs, that isn't how you set those settings.

https://cassandra.apache.org/doc/latest/cassandra/getting-started/configuring.html#environment-variables

**Comment by LaurentGoderre** [comment]
This is the smallest I have managed to get it:

```yaml
services:
  cassandra:
    image: 'cassandra:latest'
    environment:
      JVM_OPTS: -Xmn64m -Xms128m -Xmx500m
    ports:
      - '9042:9042'
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "500MB"
```
