### ISSUE TITLE
"Cassandra 3.0 and later require Java 8u40 or later" error on newer "-jammy" tags

### ISSUE THREAD

**Issue by onix** [docker-library/cassandra#281]
Hi,

with the following docker-compose.yaml

```yaml
version: '3.0'

volumes:
  cassandra-db: { }

networks:
  test-net:
    driver: bridge

services:
  cassandra-app:
    image: cassandra:3.11.17
    container_name: app-cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra-db:/var/lib/cassandra
      - ./cassandra/cassandra-311.yaml:/etc/cassandra/cassandra.yaml
    restart: unless-stopped
    networks:
      - test-net
```

when starting the `docker-compose up`, getting an error:

```
app-cassandra    | Cassandra 3.0 and later require Java 8u40 or later.
app-cassandra exited with code 1
```

faulty tags are `3.11.17`, `3.11.16`; I figured out that `-jammy` does not work, because `3.11.16-focal` container starts fine (also `3.11.16` used to work earlier, as I understand it now points to `-jammy` also).

Host system:
Docker version 20.10.7, build f0df350
docker-compose version 1.24.0, build 0aa59064
Ubuntu 16.04, 4.4.0-1168-aws, x86_64

Understand it's old, however still used to work.

Also can not reproduce this on my local dev macbook with Docker Desktop of recent version: all tags work fine.

Any ideas?
