### ISSUE TITLE
The container start before the cassandra db is up 

### ISSUE THREAD

**Issue by NIKFIORE** [docker-library/cassandra#282]
I tried to use the healtcheck , and playing with the time variable to find a right tempistic but it didn't work 

this is my docker-compose file:
```
services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    container_name: app-container
    depends_on:
      database:
        condition: service_healthy

  database:
    image: cassandra:latest
    ports:
      - 9042:9042
    container_name: cassandra-study-container
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspace"]
      interval: 30s
      timeout: 10s
      retries: 5
```
