### ISSUE TITLE
Create schema

### ISSUE THREAD

**Issue by DavidRG13** [docker-library/cassandra#65]
Hi everyone,

Is there any "standard" way of creating a schema? Or should I write my own Dockerfile/Entrypoint?

Thank you!

**Comment by varadharajan** [comment]
I came across the MySQL [entry point file](https://github.com/docker-library/mysql/blob/b4b7c8eea0690d0406a5ffc2d3404c8c42457a2d/5.6/docker-entrypoint.sh#L169) and i would prefer something like that.

**Comment by shankarshastri** [comment]
```
cassandra:
    image: cassandra
    ports:
    - "9042:9042"
    - "9160:9160"
    hostname: cassandra
    container_name: cassandra
    volumes:
      - ./random_path/random.cql:/tmp/random.cql
    command: >
            bash -c "((sleep 20s && cqlsh < /tmp/random.cql &) 
            && (/docker-entrypoint.sh cassandra -f)"
```
I did it like this with docker-compose.yml
In case of normal docker, we may need to wait for cassandra to come up. And once it's up, then you may need to exec into the docker container using
```
docker cp /random_path/random.cql cassandra:/tmp/random.cql
docker exec -i cassandra bash -c "cqlsh < /tmp/random.cql"
```
Or  you can mount the cql files before as shown above in docker-compose.yml file.
And then run exec commands.
