### ISSUE TITLE
Metrics Reporting

### ISSUE THREAD

**Issue by outrunthewolf** [docker-library/cassandra#72]
I've been through these posts a few times now, and i'm stumped as to how I can get it working with the docker image.

 - http://www.datastax.com/dev/blog/pluggable-metrics-reporting-in-cassandra-2-0-2
 - https://www.pythian.com/blog/monitoring-cassandra-grafana-influx-db/

```yml
cassandra-master:
  image: cassandra:3.0
  container_name: cassandra-master
  ulimits:
    nproc: 2048
  environment:
    - JAVA_OPTS="-Xmx1g"
    - JVM_OPTS="$JVM_OPTS -Dcassandra.metricsReporterConfigFile=influxreporting.yaml"
    - CASSANDRA_CLUSTER_NAME="My Cluster"
    - CASSANDRA_START_RPC=true
  volumes:
    - /home/cassandra/config/cassandra/metrics-graphite-2.2.0.jar:/usr/share/cassandra/lib/metrics-graphite-2.2.0.jar
    - /home/cassandra/config/cassandra/influx-reporting.yaml:/etc/cassandra/influxreporting.yaml
  privileged: true
  links:
    - influx-db:influxdb
  ports:
    - "7000:7000"
    - "7001:7001"
    - "7199:7199"
    - "9042:9042"
    - "9160:9160"
```

I simply receive an output along the lines of:

```
cassandra-master | Error: Could not find or load main class "
```

Anyone else got this working and if so how?
